[package]
authors = ["Cristi Cobzarenco <cristi.cobzarenco@gmail.com>"]
name = "rethink"
version = "0.1.0"

[dependencies]
bufstream = "0.1.3"
byteorder = "1.1.0"
failure = "0.1.0"
failure_derive = "0.1.0"
serde = "1.0.21"
serde_derive = "1.0.21"
serde_json = "1.0.6"
